cc_library(
	name = "text",
	hdrs = [
		"document.h",
		"stringbuffer.h",
		"writer.h",
		"reader.h",
		"allocators.h",
		"rapidjson.h",
		"stream.h",
		"encodings.h",
		"encodedstream.h",
		"memorystream.h",

		"fwd.h",             
		"memorybuffer.h",
		"ostreamwrapper.h",
		"filereadstream.h",
		"pointer.h",         
		"cursorstreamwrapper.h",
		"istreamwrapper.h",
		"prettywriter.h",
		"schema.h"
	],
	visibility = ["//mediapipe/examples/desktop:__pkg__"],
	deps = [
		"//mediapipe/rapidjson/internal:text",
		"//mediapipe/rapidjson/error:text"
	]
)
