cc_library(
	name = "text",
	hdrs = [
		"clzll.h",
		"meta.h",
		"stack.h",
		"swap.h",
		"strtod.h",
		"biginteger.h",
		"diyfp.h",
		"pow10.h",
		"strfunc.h",
		"dtoa.h",
		"itoa.h",
		"ieee754.h",
		"regex.h"
	],
	visibility = ["//mediapipe/rapidjson:__pkg__"],
)
